name: moday-frontend
region: nyc

services:
  - name: web
    # Usar Dockerfile para build
    dockerfile_path: Dockerfile
    build_command: ""
    
    # Porta HTTP
    http_port: 3000
    
    # Health check
    health_check:
      http_path: /
      port: 3000
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Recursos do container
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Variáveis de ambiente
    envs:
      - key: NODE_ENV
        value: "production"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3000"
      - key: HOSTNAME
        value: "0.0.0.0"
      # Adicione suas variáveis de ambiente aqui
      # - key: NEXT_PUBLIC_API_URL
      #   value: "https://sua-api.com"
